### ISSUE TITLE
As a user, I can receive incoming bluetooth data

### ISSUE THREAD

**Issue by zakuArbor** [Sxx125/proxyAuth#3]
Implement a program in C that can receive data from bluetooth

If possible, coordinate with the Android team to test the program. If not, implement a client that sends data via bluetooth to the receiver.

**Comment by zakuArbor** [comment]
For those I assigned the issue to, please discuss among yourself how to work on the issue. I just assigned the issue to the three who are not working on Android. I think this issue will be suitable for all three of you because PAM development is currently on halt till we can get bluetooth to work on the VMs. If any of you have a external bluetooth adapter or can get bluetooth working on their VMs, you can work on the PAM issue #1 instead. I will be working on issue #1 on my personal laptop since I do not mind reinstalling the OS if I mess up with the configurations.

**Comment by kay911kay** [comment]
Once pairing is done we can either use   
1.  `https://linux.die.net/man/8/hcidump` to dump raw data being transmitted between the connection  
Additionally to set up the initial pairing between the devices I suggest we use  
1. `https://linux.die.net/man/1/rfcomm ` and disable encryption and authentication to verify is "hello world" is being correctly sent from #4

**Comment by zakuArbor** [comment]
I just want to note, for this issue, you should be working on your own machines and not a virtual machine since your machines should have bluetooth support. 

The Bluetooth library we are using is for Linux but you should be able to install it on Windows using Linux Subsystem or Ubuntu on Windows if I recall correctly (I haven't owned a Windows Computer for a few years). For those of you with a Mac, you can install the header files manually and see if it works on Mac.

**Comment by kay911kay** [comment]
Opted to listen to a serial rfcomm connection instead of hcidump

**Comment by zakuArbor** [comment]
Commit `cd1a9194c203ab8846d8eae155c0caff939a16b8` can read a single input from the Android App. I used the following resources to help implement this. This issue needs to be worked on more to allow multiple receives.

**Resources:**
[https://github.com/RyanGlScott/BluetoothTest/blob/master/C%20BlueZ%20Server/bluez_server.c](https://github.com/RyanGlScott/BluetoothTest/blob/master/C%20BlueZ%20Server/bluez_server.c)
[https://people.csail.mit.edu/albert/bluez-intro/x604.html#sdpdesc](https://people.csail.mit.edu/albert/bluez-intro/x604.html#sdpdesc)

**Comment by kay911kay** [comment]
Issue Closed - Setup SDP server + RFCOMM serial connection to recv data
Commit: cd1a9194c203ab8846d8eae155c0caff939a16b8
