### ISSUE TITLE
Android: Send messages through the Android Application to the Desktop via Bluetooth

### ISSUE THREAD

**Issue by zakuArbor** [Sxx125/proxyAuth#4]
**Goal:**
* Send a message such as "Hello World" to the desktop via Bluetooth from the App

You can talk to those working on #3 to test your application.

**Comment by kay911kay** [comment]
Please take a look at 
https://developer.android.com/reference/android/bluetooth/le/AdvertiseSettings.html
I believe we can adjust txPower to change transmit range.

**Comment by zakuArbor** [comment]
Commit `531abb7eae75a866064e90434a132b2763781f2a` implemented sending data to the desktop.
I have tested it initially with [someone's work] I found on tGithub to quickly do some testing as issue #3 is being worked on.
